### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException

### ISSUE THREAD

**Issue by marxsk** [amrrs/Google-Play-Store-Review-Extractor#2]
The app does not work anymore due to changes on the web pages:

selenium.common.exceptions.NoSuchElementException: Message: no such element:
Unable to locate element: {"method":"class name","selector":"id-app-title"}

I understand that this app is no longer under active development, so this is just a notice for potential users.

**Comment by amrrs** [comment]
Thanks for noifying this. If it could help anyone I'm happy to look into it
On 30 Aug 2018, at 3:56 PM, "Marek Grác" <notifications@github.com<mailto:notifications@github.com>> wrote:

The app does not work anymore due to changes on the web pages:

selenium.common.exceptions.NoSuchElementException: Message: no such element:
Unable to locate element: {"method":"class name","selector":"id-app-title"}

I understand that this app is no longer under active development, so this is just a notice for potential users.

**Comment by marxsk** [comment]
@amrrs thanks a lot. But I have found a different app/library for this problem.

**Comment by amrrs** [comment]
Could you please share that @marxsk . It'll help others who come here.

**Comment by marxsk** [comment]
@amrrs I'm using https://github.com/facundoolano/google-play-scraper

**Comment by amrrs** [comment]
Thank you @marxsk  for sharing it!
